--- 
document: 
  name: "Modello Aziende sanitarie locali (ASL)"
  description: "Documentazione tecnica e di progetto del modello ASL di Designers Italia. Scopri cos'è il modello, come usare le risorse disponibili e il processo di ricerca alla base della progettazione."
  tags:
    - siti web
    - design
    - asl
